# Generated by Django 4.0.4 on 2022-05-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='air_p',
            field=models.IntegerField(blank=True, null=True, verbose_name='Air pressure'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='bright',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brightness'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='humi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_humi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Soil humidity'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature'),
        ),
    ]
