# Generated by Django 4.0.4 on 2022-06-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='air_p',
            field=models.FloatField(blank=True, null=True, verbose_name='Air pressure'),
        ),
    ]
