# Generated by Django 4.0.4 on 2022-06-03 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_sensor_air_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
